Repository TEAM-2NE1/steach-server, pull requests merged in 2024-08, with the labels that each got.

#106 feat: 레디스 사용 및 테스트 폴더 구조 변경
  build.gradle
  src/main/java/com/twentyone/steachserver/SteachServerApplication.java
  src/main/java/com/twentyone/steachserver/config/RedisConfig.java
  src/main/java/com/twentyone/steachserver/config/security/SecurityConfiguration.java
  src/main/java/com/twentyone/steachserver/domain/auth/model/LoginCredential.java
  src/main/java/com/twentyone/steachserver/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/common/BaseTimeEntity.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumDetailResponse.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumListResponse.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/model/Curriculum.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumRepository.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumSearchRepository.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/service/batch/CurriculumBatchService.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/service/redis/CurriculumRedisService.java
  src/main/java/com/twentyone/steachserver/domain/quiz/model/QuizChoice.java
  src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizChoiceService.java
  src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizChoiceServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/quiz/validator/QuizChoiceValidator.java
  src/main/java/com/twentyone/steachserver/domain/studentLecture/model/StudentLecture.java
  src/main/java/com/twentyone/steachserver/interfaces/advice/GlobalControllerAdvice.java
  src/main/java/com/twentyone/steachserver/interfaces/main/MainCurriculumController.java
  src/main/java/com/twentyone/steachserver/interfaces/status/ServerStatusController.java
  src/main/java/com/twentyone/steachserver/util/converter/DateTimeUtil.java
  src/main/java/com/twentyone/steachserver/util/converter/FileUtil.java
  src/main/java/com/twentyone/steachserver/util/converter/WeekdayBitmaskUtil.java
  src/test/java/com/twentyone/steachserver/SteachTest.java
  src/test/java/com/twentyone/steachserver/TestScenario1.java
  src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImplTest.java
  src/test/java/com/twentyone/steachserver/integration/curriculum/service/CurriculumServiceIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizChoiceServiceIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizIntegrationTest.java
  src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumRedisServiceTest.java
  src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumServiceImplTest.java
  src/test/java/com/twentyone/steachserver/unit/domain/quiz/service/QuizChoiceServiceImplTest.java
  src/test/java/com/twentyone/steachserver/unit/domain/quiz/validator/QuizChoiceValidatorTest.java
Labels: 👍 enhancement

#107 사용자와 강의 사이의 통신 기능 추가
  src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumIncludesStudentDto.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumIncludesStudentListResponseDto.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/model/CurriculumDetail.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/member/memberController/StudentController.java
  src/main/java/com/twentyone/steachserver/domain/member/memberController/TeacherController.java
  src/main/java/com/twentyone/steachserver/domain/studentCurriculum/dto/IsApplyForCurriculumResponseDto.java
  src/main/java/com/twentyone/steachserver/domain/studentCurriculum/repository/StudentCurriculumRepository.java
Labels: 👍 enhancement

#108 feat: 강의 시간도 수정가능하도록 변경
  src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java
  src/main/java/com/twentyone/steachserver/domain/lecture/dto/update/UpdateLectureRequestDto.java
  src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java
  src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java
Labels: 👍 enhancement

#109 fix: StudentLecture를 중복으로 만드는 로직 수정
  src/main/java/com/twentyone/steachserver/domain/classroom/controller/ClassroomController.java
  src/main/java/com/twentyone/steachserver/domain/classroom/service/ClassroomServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/studentLecture/service/StudentLectureService.java
  src/main/java/com/twentyone/steachserver/domain/studentLecture/service/StudentLectureServiceImpl.java
  src/test/java/com/twentyone/steachserver/TestScenario1.java
Labels: 🔥 bug

#110 커리큘럼 카테고리 종류 변경 EDUCATION -> SOCIAL
  src/main/java/com/twentyone/steachserver/config/WebConfig.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/enums/CurriculumCategory.java
  src/main/resources/sql/finalSchema.sql
  src/test/java/com/twentyone/steachserver/TestScenario1.java
  src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java
  src/test/java/com/twentyone/steachserver/integration/curriculum/controller/CurriculumControllerIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/curriculum/service/CurriculumServiceIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizIntegrationTest.java
  src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumRedisServiceTest.java
  src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumServiceImplTest.java
Labels: 👍 enhancement

#112 카테고리 변경으로 인한 테스트 충돌 해결
  build.gradle
  src/test/java/com/twentyone/steachserver/TestScenario1.java
  src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java
  src/test/java/com/twentyone/steachserver/integration/curriculum/controller/CurriculumControllerIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/curriculum/service/CurriculumServiceIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizIntegrationTest.java
  src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumRealRedisServiceTest.java
  src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumRedisServiceTest.java
  src/test/java/com/twentyone/steachserver/unit/domain/curriculum/service/CurriculumServiceImplTest.java
Labels: 🔥 bug, 👍 enhancement

#116 퀴즈 여러 개 수정기능 구현
  src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureRepository.java
  src/main/java/com/twentyone/steachserver/domain/quiz/controller/QuizController.java
  src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizResponseDto.java
  src/main/java/com/twentyone/steachserver/domain/quiz/model/Quiz.java
  src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizService.java
  src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java
  src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizIntegrationTest.java
Labels: 👍 enhancement

#118 refactor: 서버 확인용 uri 권한 삭제
  src/main/java/com/twentyone/steachserver/config/security/SecurityConfiguration.java
Labels: 👍 enhancement

#131 중복확인 API 구현
  src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java
  src/main/java/com/twentyone/steachserver/domain/auth/dto/CheckUsernameAvailableResponse.java
  src/main/java/com/twentyone/steachserver/domain/member/repository/StudentRepository.java
  src/main/java/com/twentyone/steachserver/domain/member/repository/TeacherRepository.java
  src/main/java/com/twentyone/steachserver/domain/member/service/StudentService.java
  src/main/java/com/twentyone/steachserver/domain/member/service/StudentServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/member/service/TeacherService.java
  src/main/java/com/twentyone/steachserver/domain/member/service/TeacherServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizRequestDto.java
  src/main/java/com/twentyone/steachserver/domain/quiz/model/Quiz.java
  src/test/java/com/twentyone/steachserver/TestScenario1.java
  src/test/java/com/twentyone/steachserver/integration/quiz/service/QuizIntegrationTest.java
Labels: 👍 enhancement

#142 sonarqube 자동화 추가
  Jenkinsfile
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  jacoco.gradle
  sonarqube.gradle
Labels: 🐬 documentation, 👍 enhancement

#169 강의가 끝난 후, 강의에 대한 레포트 조회 API 추가
  src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java
  src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureBeforeStartingResponseDto.java
  src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/studentQuiz/controller/StudentQuizController.java
  src/main/java/com/twentyone/steachserver/domain/studentQuiz/service/StudentQuizServiceImpl.java
Labels: 👍 enhancement

#173 나의 강의 히스토리 API 생성
  src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java
  src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureHistoryResponse.java
  src/main/java/com/twentyone/steachserver/domain/lecture/dto/MyLectureHistoryResponse.java
  src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java
  src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureService.java
  src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/quiz/repository/QuizStatisticsRepository.java
  src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/studentQuiz/repository/StudentQuizRepository.java
  src/main/java/com/twentyone/steachserver/domain/studentQuiz/service/StudentQuizServiceImpl.java
Labels: 👍 enhancement

#176 refactor: print문 삭제
  src/main/java/com/twentyone/steachserver/config/RedisConfig.java
  src/main/java/com/twentyone/steachserver/domain/gpt/service/GPTServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/lecture/model/Lecture.java
  src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureQueryRepository.java
  src/test/java/com/twentyone/steachserver/SteachTest.java
  src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java
  src/test/java/com/twentyone/steachserver/config/TestRedisConfig.java
  src/test/java/com/twentyone/steachserver/helper/DatabaseCleanup.java
  src/test/java/com/twentyone/steachserver/integration/auth/controller/TeacherAuthControllerIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/curriculum/controller/CurriculumControllerIntegrationTest.java
  src/test/java/com/twentyone/steachserver/unit/RedisConfigInfoTest.java
Labels: 🐬 documentation

#182 퀴즈 통계 순위 내림차순으로 안나오는 에러 해결
  src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/studentQuiz/repository/StudentQuizRepository.java
Labels: 👍 enhancement

#186 퀴즈 통계 순위 랭크 순서 제대로 안나오는 에러 수정
  src/main/java/com/twentyone/steachserver/domain/quiz/dto/QuizStudentScoreDto.java
  src/main/java/com/twentyone/steachserver/domain/quiz/service/QuizServiceImpl.java
Labels: 🔥 bug
