Repository TEAM-2NE1/steach-server, pull requests merged in 2024-07, with the labels that each got.

#49 docs: 여러 상황의 이슈 템플릿 생성 및 PR 템플릿 스타일 수정
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/CHORE.md
  .github/ISSUE_TEMPLATE/DOCUMENTATION.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT.md
  .github/ISSUE_TEMPLATE/HELP_WANT.md
  .github/ISSUE_TEMPLATE/INFRA.md
  .github/ISSUE_TEMPLATE/INVALID.md
  .github/ISSUE_TEMPLATE/Invaild.md
  .github/ISSUE_TEMPLATE/QUESTION.md
  .github/ISSUE_TEMPLATE/WONTFIX.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🐬 documentation, 👍 enhancement

#75 refactor: 통계로직 오류 해결
  src/main/java/com/twentyone/steachserver/domain/lecture/controller/LectureController.java
  src/main/java/com/twentyone/steachserver/domain/statistic/controller/StatisticController.java
  src/main/java/com/twentyone/steachserver/domain/statistic/dto/StatisticsByCurriculumCategory.java
  src/main/java/com/twentyone/steachserver/domain/statistic/model/RadarChartStatistic.java
  src/main/java/com/twentyone/steachserver/domain/statistic/model/mongo/GPTDataByLecture.java
  src/main/java/com/twentyone/steachserver/domain/statistic/repository/GPTDataByLectureMongoRepository.java
  src/main/java/com/twentyone/steachserver/domain/statistic/repository/LectureStatisticMongoRepository.java
  src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticService.java
  src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureQueryRepository.java
Labels: 👍 enhancement, ⚠️invalid

#92 Fix: 사용되지 않는 메서드 수정
  src/main/java/com/twentyone/steachserver/config/ConstructConfiguration.java
  src/main/java/com/twentyone/steachserver/domain/classroom/repository/ClassroomQueryRepository.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumSearchRepository.java
  src/main/java/com/twentyone/steachserver/domain/lecture/repository/LectureQueryRepository.java
  src/main/java/com/twentyone/steachserver/domain/studentLecture/repository/StudentLectureQueryRepository.java
Labels: 🔥 bug

#95 test 코드 일부 작성 및 비밀번호 확인 로직 추가
  build.gradle
  src/main/java/com/twentyone/steachserver/domain/auth/controller/AuthController.java
  src/main/java/com/twentyone/steachserver/domain/auth/dto/MemberCheckPasswordRequestDto.java
  src/main/java/com/twentyone/steachserver/domain/auth/dto/MemberCheckPasswordResponseDto.java
  src/main/java/com/twentyone/steachserver/domain/auth/service/AuthService.java
  src/main/java/com/twentyone/steachserver/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumAddRequest.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/member/dto/TeacherInfoRequest.java
  src/test/java/com/twentyone/steachserver/auth/WithAuthTeacher.java
  src/test/java/com/twentyone/steachserver/auth/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/twentyone/steachserver/domain/IntegrationTests.java
  src/test/java/com/twentyone/steachserver/domain/TempTest.java
Labels: 👍 enhancement

#99 인수테스트 완료
  src/main/java/com/twentyone/steachserver/domain/studentQuiz/dto/StudentQuizDto.java
  src/main/java/com/twentyone/steachserver/domain/studentQuiz/dto/StudentQuizRequestDto.java
  src/main/java/com/twentyone/steachserver/util/HealthController.java
  src/test/java/com/twentyone/steachserver/SteachServerApplicationTests.java
  src/test/java/com/twentyone/steachserver/acceptance/AcceptanceTest.java
  src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java
  src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImplTest.java
  src/test/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceIntegrationTest.java
  src/test/java/com/twentyone/steachserver/domain/quiz/service/QuizChoiceServiceImplTest.java
  src/test/java/com/twentyone/steachserver/domain/quiz/service/QuizIntegrationTest.java
  src/test/java/com/twentyone/steachserver/helper/ServerManager.java
  src/test/java/com/twentyone/steachserver/integration/ControllerIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/auth/controller/AuthControllerIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/auth/controller/TeacherAuthControllerIntegrationTest.java
  src/test/java/com/twentyone/steachserver/integration/curriculum/controller/CurriculumControllerIntegrationTest.java
Labels: 👍 enhancement

#105 gpt관련 통계 수정, 커리큘럼 페이징 수정, 강의조회 주단위 나누기 추가
  src/main/java/com/twentyone/steachserver/domain/curriculum/controller/CurriculumController.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/dto/CurriculumListResponse.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumRepository.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/repository/CurriculumSearchRepository.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumService.java
  src/main/java/com/twentyone/steachserver/domain/curriculum/service/CurriculumServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/lecture/dto/AllLecturesInCurriculaResponseDto.java
  src/main/java/com/twentyone/steachserver/domain/lecture/dto/LectureResponseDto.java
  src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureService.java
  src/main/java/com/twentyone/steachserver/domain/lecture/service/LectureServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/member/memberController/StudentController.java
  src/main/java/com/twentyone/steachserver/domain/member/memberController/TeacherController.java
  src/main/java/com/twentyone/steachserver/domain/statistic/model/mongo/GPTDataByLecture.java
  src/main/java/com/twentyone/steachserver/domain/statistic/repository/GPTDataByLectureMongoRepository.java
  src/main/java/com/twentyone/steachserver/domain/statistic/service/StatisticServiceImpl.java
  src/main/java/com/twentyone/steachserver/domain/studentCurriculum/repository/StudentCurriculumRepository.java
  src/main/java/com/twentyone/steachserver/domain/studentLecture/service/StudentLectureServiceImpl.java
  src/test/java/com/twentyone/steachserver/TestScenario1.java
  src/test/java/com/twentyone/steachserver/acceptance/MainAcceptanceTest.java
Labels: 👍 enhancement
